// GENERATED by gravelmon-submission-app/scripts/build-models-template.ts from src/models-ci/cli/sync-credits.cli.ts.
// Do not edit: change the source and run `npm run build:models-template`.

// src/models-ci/syncCredits.ts
import { execFileSync } from "node:child_process";

// src/services/remote/aspectOrder.json
var aspectOrder_default = {
  alolan: 1,
  female: 2,
  galarian: 3,
  hisuian: 4,
  paldean: 5,
  valencian: 6,
  cosplay: 7,
  world: 8,
  gmax: 9,
  starter: 10,
  partner: 11,
  kalos: 12,
  unova: 13,
  sinnoh: 14,
  libre: 15,
  phd: 16,
  pop_star: 17,
  belle: 18,
  rock_star: 19,
  mega: 20,
  sunny: 21,
  rainy: 22,
  snowy: 23,
  hoennian: 24,
  x: 25,
  storm: 26,
  fairy: 27,
  dragon: 28,
  psychic: 29,
  sound: 30,
  water: 31,
  steel: 32,
  ground: 33,
  poison: 34,
  rock: 35,
  grass: 36,
  flying: 37,
  fighting: 38,
  electric: 39,
  dark: 40,
  ice: 41,
  ghost: 42,
  fire: 43,
  red: 44,
  green: 45,
  yellow: 46,
  monster: 47,
  summer: 48,
  school: 49,
  swarm: 50,
  dry: 51,
  sirius: 52,
  altair: 53,
  one: 54,
  two: 55,
  three: 56,
  four: 57,
  five: 58,
  six: 59,
  seven: 60,
  eight: 61,
  nine: 62,
  ten: 63,
  eleven: 64,
  twelve: 65,
  thirteen: 66,
  fourteen: 67,
  fifteen: 68,
  sixteen: 69,
  seventeen: 70,
  eighteen: 71,
  nineteen: 72,
  twenty: 73,
  twentyone: 74,
  twentytwo: 75,
  twentythree: 76,
  twentyfour: 77,
  twentyfive: 78,
  twentysix: 79,
  twentyseven: 80,
  nose_pattern: 81,
  brow_pattern: 82,
  qamoran: 83,
  nostan: 84,
  varitasian: 85,
  seviian: 86,
  deep: 87,
  ayreian: 88,
  kaskadian: 89,
  mystic: 90,
  avalossian: 91,
  enjinian: 92,
  novran: 93,
  neo: 94,
  norheiman: 95,
  avorian: 96,
  hizian: 97,
  alteran: 98,
  aristosian: 99,
  armiran: 100,
  relic: 101,
  gutsy: 102,
  windy: 103,
  smoggy: 104,
  dusty: 105,
  sandy: 106,
  swarmy: 107,
  spooky: 108,
  whirly: 109,
  allergy: 110,
  zappy: 111,
  zenny: 112,
  sorcery: 113,
  shady: 114,
  lovely: 115,
  cefiran: 116,
  egho: 117,
  delta: 118,
  spider: 119,
  ruin: 120,
  berry: 121,
  cake: 122,
  unleashed: 123,
  inactive: 124,
  crystal: 125,
  active: 126,
  blaze_boost: 127,
  armored: 128,
  magician: 129,
  blue: 130,
  exothermic: 131,
  hubian: 132,
  earth: 133,
  havaiiian: 134,
  lagoonan: 135,
  rican: 136,
  crozoican: 137,
  interian: 138,
  signetan: 139,
  okenian: 140,
  lost_islands: 141,
  space: 142,
  sage_space: 143,
  beta: 144,
  terrestrial: 145,
  xenoversal: 146,
  astral: 147,
  mix: 148,
  twirl: 149,
  bass: 150,
  home: 151,
  junk: 152,
  web: 153,
  brawl: 154,
  sway: 155,
  sol: 156,
  amaze_all: 157,
  eldiwan: 158,
  winter_coat: 159,
  summer_coat: 160,
  xenoverse: 161,
  africanusan: 162,
  vesitan: 163,
  epoch: 164,
  tokassian: 165,
  pastelian: 166,
  nodorran: 167,
  olysosian: 168,
  ottoran: 169,
  mystisian: 170,
  mastenian: 171,
  theossian: 172,
  dhioman: 173,
  ionosian: 174,
  forman: 175,
  raianian: 176,
  tribal: 177,
  norse: 178,
  palmian: 179,
  trizoran: 180,
  forest: 181,
  cave: 182,
  sea: 183,
  ivrisian: 184,
  ferranian: 185,
  mahalian: 186,
  fabelian: 187,
  sahlian: 188,
  elbian: 189,
  aromian: 190,
  mikitarian: 191,
  ishirian: 192,
  shadow: 193,
  guitarist: 194,
  drummer: 195,
  bassist: 196,
  nuclear: 197
};

// src/services/remote/gravelmonPaths.ts
var ASPECT_ORDER = aspectOrder_default;
var ASPECT_BY_ORDINAL = new Map(
  Object.entries(ASPECT_ORDER).map(([aspect, order]) => [order, aspect])
);

// src/services/remote/rawFileClient.ts
var COBBLEMON_PROJECT_PATH = encodeURIComponent("cable-mc/cobblemon");

// src/gravelmon-models/formFolder.ts
function isValidFolderSegment(segment) {
  return /^[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(segment) && !segment.endsWith(".") && segment !== "..";
}
function parseFormFolderPath(path) {
  const segments = path.split("/");
  if (segments.length !== 2 || !segments.every(isValidFolderSegment)) {
    return void 0;
  }
  return { game: segments[0], folder: segments[1] };
}

// src/models-ci/pullRequests.ts
var HOLDING_BRANCH = "holding/holding-branch";
var MAIN_BRANCH = "main";
function isVersionBranch(name) {
  return /^\d+\.\d+\.\d+$/.test(name);
}
function isInitialHop(input) {
  const holding = input.holdingBranch ?? HOLDING_BRANCH;
  const { pr } = input;
  return pr !== void 0 && input.ref === `refs/heads/${holding}` && pr.baseRef === holding && pr.headRef !== holding && !isVersionBranch(pr.headRef) && pr.headRef !== MAIN_BRANCH;
}
async function resolveMergedPullRequest(github, sha, baseRef) {
  const all = await github.listPullRequestsAssociatedWithCommit(sha);
  return all.find((pr) => pr.merged && (baseRef === void 0 || pr.baseRef === baseRef));
}

// src/gravelmon-species/sha256.ts
var K = new Uint32Array([
  1116352408,
  1899447441,
  3049323471,
  3921009573,
  961987163,
  1508970993,
  2453635748,
  2870763221,
  3624381080,
  310598401,
  607225278,
  1426881987,
  1925078388,
  2162078206,
  2614888103,
  3248222580,
  3835390401,
  4022224774,
  264347078,
  604807628,
  770255983,
  1249150122,
  1555081692,
  1996064986,
  2554220882,
  2821834349,
  2952996808,
  3210313671,
  3336571891,
  3584528711,
  113926993,
  338241895,
  666307205,
  773529912,
  1294757372,
  1396182291,
  1695183700,
  1986661051,
  2177026350,
  2456956037,
  2730485921,
  2820302411,
  3259730800,
  3345764771,
  3516065817,
  3600352804,
  4094571909,
  275423344,
  430227734,
  506948616,
  659060556,
  883997877,
  958139571,
  1322822218,
  1537002063,
  1747873779,
  1955562222,
  2024104815,
  2227730452,
  2361852424,
  2428436474,
  2756734187,
  3204031479,
  3329325298
]);

// src/gravelmon-species/speciesKeys.ts
var CATALOG_INDEX = "gsi-catalog";
var BULK_INDEX = "gsi-bulk";
var CHANGE_REQUEST_INDEX = "gsi-cr";
var CATALOG_PROJECTED_ATTRIBUTES = [
  "formId",
  "addedByGame",
  "source",
  "revision",
  "catalogue",
  "name",
  "primaryType",
  "secondaryType",
  "preEvolution",
  "abilities"
];
var SPECIES_TABLE_SCHEMA = {
  keySchema: [
    { AttributeName: "pk", KeyType: "HASH" },
    { AttributeName: "sk", KeyType: "RANGE" }
  ],
  attributeDefinitions: [
    { AttributeName: "pk", AttributeType: "S" },
    { AttributeName: "sk", AttributeType: "S" },
    { AttributeName: "cpk", AttributeType: "S" },
    { AttributeName: "csk", AttributeType: "S" },
    { AttributeName: "bpk", AttributeType: "S" },
    { AttributeName: "bsk", AttributeType: "S" },
    { AttributeName: "crpk", AttributeType: "S" },
    { AttributeName: "crsk", AttributeType: "S" }
  ],
  globalSecondaryIndexes: [
    {
      IndexName: CATALOG_INDEX,
      KeySchema: [
        { AttributeName: "cpk", KeyType: "HASH" },
        { AttributeName: "csk", KeyType: "RANGE" }
      ],
      Projection: {
        ProjectionType: "INCLUDE",
        NonKeyAttributes: [...CATALOG_PROJECTED_ATTRIBUTES]
      }
    },
    {
      IndexName: BULK_INDEX,
      KeySchema: [
        { AttributeName: "bpk", KeyType: "HASH" },
        { AttributeName: "bsk", KeyType: "RANGE" }
      ],
      Projection: { ProjectionType: "ALL" }
    },
    {
      IndexName: CHANGE_REQUEST_INDEX,
      KeySchema: [
        { AttributeName: "crpk", KeyType: "HASH" },
        { AttributeName: "crsk", KeyType: "RANGE" }
      ],
      Projection: { ProjectionType: "ALL" }
    }
  ]
};

// src/gravelmon-species/speciesItems.ts
var RESERVED_FIELDS = /* @__PURE__ */ new Set([
  "pk",
  "sk",
  "formId",
  "addedByGame",
  "source",
  "revision",
  "origin",
  "catalogue",
  "lang",
  "cpk",
  "csk",
  "bpk",
  "bsk"
]);
var IMMUTABLE_FIELDS = new Set(
  [...RESERVED_FIELDS].filter((name) => name !== "lang")
);

// src/gravelmon-species/speciesPatch.ts
var MAX_VALUE_BYTES = 64 * 1024;

// src/gravelmon-tags/tagCodec.ts
var MAX_TAG_JSON_BYTES = 128 * 1024;

// src/models-ci/runtime.ts
var ConfigError = class extends Error {
};
function requireEnv(env, name) {
  const value = env[name];
  if (value === void 0 || value.trim() === "") {
    throw new ConfigError(`${name} is not set.`);
  }
  return value;
}
function optionalEnv(env, name) {
  const value = env[name];
  return value === void 0 || value.trim() === "" ? void 0 : value.trim();
}
function parsePrNumber(raw, label = "pr_number") {
  if (raw === void 0 || raw.trim() === "") {
    return void 0;
  }
  if (!/^\d+$/.test(raw.trim()) || Number(raw) <= 0) {
    throw new ConfigError(`${label} must be a positive integer, not "${raw}".`);
  }
  return Number(raw.trim());
}
function annotate(level, message) {
  const escaped = message.replace(/%/g, "%25").replace(/\r/g, "%0D").replace(/\n/g, "%0A");
  return `::${level}::${escaped}`;
}

// src/models-ci/syncCredits.ts
var ZERO_SHA = "0000000000000000000000000000000000000000";
function isCreditsPath(path) {
  const parts = path.split("/");
  return parts.length === 3 && parts[2] === "credits.json" && parseFormFolderPath(`${parts[0]}/${parts[1]}`) !== void 0;
}
function gitReader(cwd) {
  const git = (args) => execFileSync("git", args, {
    cwd,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
    stdio: ["ignore", "pipe", "ignore"]
  }).trim();
  return {
    changedCreditsFiles(base, head) {
      return git(["diff", "--name-only", base, head, "--", ":(glob)*/*/credits.json"]).split("\n").filter((path) => path !== "" && isCreditsPath(path));
    },
    readJsonAt(ref, path) {
      try {
        return JSON.parse(git(["show", `${ref}:${path}`]));
      } catch {
        return void 0;
      }
    }
  };
}
function countClips(git, ref, path) {
  const file = git.readJsonAt(ref, path);
  return Object.keys(file?.animations ?? {}).length;
}
function collectAwards(git, base, after) {
  const diffBase = base !== "" && base !== ZERO_SHA ? base : `${after}~1`;
  const awards = /* @__PURE__ */ new Map();
  const identifiers = /* @__PURE__ */ new Set();
  const addedByGame = /* @__PURE__ */ new Map();
  for (const path of git.changedCreditsFiles(diffBase, after)) {
    const before = git.readJsonAt(diffBase, path) ?? { entries: [] };
    const now = git.readJsonAt(after, path) ?? { entries: [] };
    const fresh = (now.entries ?? []).slice((before.entries ?? []).length);
    for (const entry of fresh) {
      const aspects = entry.formAspects ?? now.formAspects ?? [];
      const identifier = `${now.game}#${now.pokemon}${aspects.length > 0 ? `#${aspects.join(",")}` : ""}`;
      identifiers.add(identifier);
      if (!addedByGame.has(identifier)) {
        addedByGame.set(identifier, path.split("/")[0]);
      }
      const login = entry.contributor.login;
      const clips = (entry.animations ?? []).reduce((sum, animation) => sum + countClips(git, after, animation), 0);
      const perForm = awards.get(login) ?? /* @__PURE__ */ new Map();
      perForm.set(identifier, (perForm.get(identifier) ?? 0) + clips);
      awards.set(login, perForm);
    }
  }
  return { identifiers: [...identifiers], addedByGame, awards };
}
async function runSyncCredits(input, deps) {
  const log = deps.log ?? ((message) => console.log(message));
  const { identifiers, addedByGame, awards } = collectAwards(deps.git, input.before, input.after);
  if (identifiers.length === 0) {
    log("No credits files changed in this push; nothing to sync.");
    return { exitCode: 0 };
  }
  let prNumber = input.prNumber;
  if (prNumber === void 0 && input.eventName === "push") {
    const pr = await resolveMergedPullRequest(deps.github, input.sha);
    if (isInitialHop({ ref: input.ref, pr, holdingBranch: input.holdingBranch })) {
      prNumber = pr?.number;
    }
  }
  const status = await deps.api.post(
    "/api/internal/pokemon-status",
    {
      // `identifiers` keep the identifier's own game; `forms` add, per entry, the game the assets are
      // filed under. An API that predates `forms` ignores it.
      identifiers,
      forms: identifiers.map((identifier) => ({ identifier, addedByGame: addedByGame.get(identifier) })),
      ...input.assetBranch ? { branch: input.assetBranch } : {}
    },
    "any"
  );
  checkItems("/api/internal/pokemon-status", status);
  if (prNumber === void 0) {
    log("No credited PR for this push (not an initial holding-branch PR); skipping point awards.");
    return { exitCode: 0 };
  }
  for (const [login, perForm] of awards) {
    const answer = await deps.api.post(
      "/api/internal/award-points",
      {
        login,
        pullRequestNumber: prNumber,
        submissions: [...perForm.entries()].map(([identifier, newAnimations]) => ({
          identifier,
          addedByGame: addedByGame.get(identifier),
          newAnimations
        }))
      },
      // A timed-out attempt may still have landed; do not risk double points.
      "never"
    );
    checkItems("/api/internal/award-points", answer);
  }
  return { exitCode: 0 };
}
function checkItems(path, answer) {
  const failed = (answer.updated ?? []).filter((item) => item.status === "error");
  if (failed.length > 0) {
    throw new Error(`${path} reported per-item errors: ${JSON.stringify(failed)}`);
  }
}
function syncInputFromEnv(env) {
  const eventName = requireEnv(env, "GITHUB_EVENT_NAME");
  const after = optionalEnv(env, "AFTER_SHA") ?? requireEnv(env, "GITHUB_SHA");
  const before = optionalEnv(env, "BEFORE_SHA");
  if (before === void 0) {
    throw new ConfigError("BEFORE_SHA is not set.");
  }
  return {
    eventName,
    ref: requireEnv(env, "GITHUB_REF"),
    sha: requireEnv(env, "GITHUB_SHA"),
    before,
    after,
    prNumber: parsePrNumber(optionalEnv(env, "PR_NUMBER")),
    assetBranch: optionalEnv(env, "ASSET_BRANCH"),
    holdingBranch: optionalEnv(env, "HOLDING_BRANCH") ?? HOLDING_BRANCH
  };
}

// src/models-ci/apiClient.ts
import { createHash } from "node:crypto";
var ApiError = class extends Error {
  constructor(message, path, status, ambiguous, responseText) {
    super(message);
    this.path = path;
    this.status = status;
    this.ambiguous = ambiguous;
    this.responseText = responseText;
    this.name = "ApiError";
  }
};
var DEFAULT_MAX_ATTEMPTS = 5;
var DEFAULT_BASE_DELAY_MS = 2e3;
var MAX_DELAY_MS = 6e4;
function sha256Hex(value) {
  return createHash("sha256").update(value, "utf8").digest("hex");
}
function retryable(policy, status) {
  if (policy === "never") {
    return false;
  }
  if (policy === "any") {
    return status === void 0 || status === 429 || status >= 500;
  }
  return status === 429 || status === 503;
}
var ApiClient = class {
  constructor(options) {
    this.domain = options.domain.replace(/\/+$/, "");
    this.token = options.token;
    this.fetchImpl = options.fetchImpl ?? ((url, init) => fetch(url, init));
    this.sleep = options.sleep ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));
    this.random = options.random ?? Math.random;
    this.maxAttempts = options.maxAttempts ?? DEFAULT_MAX_ATTEMPTS;
    this.baseDelayMs = options.baseDelayMs ?? DEFAULT_BASE_DELAY_MS;
    this.log = options.log ?? ((message) => console.log(message));
  }
  /** POSTs JSON and returns the parsed answer. Throws {@link ApiError} for anything but a 2xx JSON answer. */
  async post(path, body, retry) {
    const jsonBody = JSON.stringify(body);
    const attempts = retry === "never" ? 1 : this.maxAttempts;
    for (let attempt = 1; ; attempt++) {
      let status;
      let text;
      let retryAfterMs;
      let failure;
      try {
        const response = await this.fetchImpl(`${this.domain}${path}`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-Gravelmon-Token": `Bearer ${this.token}`,
            "x-amz-content-sha256": sha256Hex(jsonBody)
          },
          body: jsonBody
        });
        status = response.status;
        text = await response.text();
        const retryAfter = Number(response.headers.get("retry-after"));
        retryAfterMs = Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1e3 : void 0;
        if (response.ok) {
          this.log(`${path} -> ${status}: ${text}`);
          return parseJson(path, status, text);
        }
        failure = `${path} -> ${status}: ${text}`;
      } catch (cause) {
        if (cause instanceof ApiError) {
          throw cause;
        }
        failure = `${path} failed: ${cause instanceof Error ? cause.message : String(cause)}`;
      }
      if (!retryable(retry, status) || attempt >= attempts) {
        const ambiguous = retry !== "any" && (status === void 0 || status >= 500 && status !== 503);
        throw new ApiError(
          ambiguous ? `${failure} (ambiguous: the write may have landed)` : failure,
          path,
          status,
          ambiguous,
          text
        );
      }
      const delay = Math.min(
        Math.max(this.baseDelayMs * 2 ** (attempt - 1) + this.random() * 1e3, retryAfterMs ?? 0),
        MAX_DELAY_MS
      );
      this.log(`${path} attempt ${attempt}/${attempts} failed (${failure}); retrying in ${Math.round(delay)}ms.`);
      await this.sleep(delay);
    }
  }
};
function parseJson(path, status, text) {
  try {
    return JSON.parse(text);
  } catch {
    throw new ApiError(`${path} -> ${status}: the answer is not JSON: ${text.slice(0, 200)}`, path, status, false, text);
  }
}

// src/models-ci/github.ts
var GithubError = class extends Error {
  constructor(message, status) {
    super(message);
    this.status = status;
    this.name = "GithubError";
  }
};
function toPullRequestInfo(raw) {
  return {
    number: raw.number,
    body: raw.body ?? "",
    baseRef: raw.base.ref,
    headRef: raw.head.ref,
    merged: raw.merged === true || raw.merged_at !== void 0 && raw.merged_at !== null,
    authorLogin: raw.user?.login ?? "",
    authorType: raw.user?.type ?? "",
    ...raw.state === void 0 ? {} : { closed: raw.state === "closed" }
  };
}
var GithubRest = class {
  constructor(options) {
    this.repository = options.repository;
    this.token = options.token;
    this.fetchImpl = options.fetchImpl ?? ((url, init) => fetch(url, init));
    this.baseUrl = options.baseUrl ?? "https://api.github.com";
  }
  /** The pull requests GitHub associates with a commit (the lookup the credit sync always used). */
  async listPullRequestsAssociatedWithCommit(sha) {
    const response = await this.send("GET", `/commits/${encodeURIComponent(sha)}/pulls?per_page=100`);
    return (await response.json()).map(toPullRequestInfo);
  }
  async getPullRequest(number) {
    const response = await this.send("GET", `/pulls/${number}`);
    return toPullRequestInfo(await response.json());
  }
  /** A comment on a pull request (pull requests are issues for comments). */
  async comment(number, body) {
    await this.send("POST", `/issues/${number}/comments`, { body });
  }
  /** The commit a tag points at, or `undefined` when there is no such tag. Lightweight tags only. */
  async getTag(tag) {
    const response = await this.send("GET", `/git/ref/tags/${encodeURIComponent(tag)}`, void 0, [404]);
    if (response.status === 404) {
      return void 0;
    }
    const body = await response.json();
    return { sha: body.object.sha, type: body.object.type };
  }
  /** Creates `refs/tags/<tag>` at a commit. Fails (422) if it exists: a tag is never moved. */
  async createTag(tag, sha) {
    await this.send("POST", "/git/refs", { ref: `refs/tags/${tag}`, sha });
  }
  /**
   * Deletes `refs/heads/<branch>`. `missing` when there is no such branch (404, or 422 "Reference does
   * not exist"): the job is "make sure it is gone", so a branch that already is, is a success.
   */
  async deleteBranch(branch) {
    const path = `/git/refs/heads/${branch.split("/").map(encodeURIComponent).join("/")}`;
    const response = await this.send("DELETE", path, void 0, [404, 422]);
    return response.ok ? "deleted" : "missing";
  }
  async send(method, path, body, accept = []) {
    const response = await this.fetchImpl(`${this.baseUrl}/repos/${this.repository}${path}`, {
      method,
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${this.token}`,
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "gravelmon-models-ci",
        ...body === void 0 ? {} : { "Content-Type": "application/json" }
      },
      body: body === void 0 ? void 0 : JSON.stringify(body)
    });
    if (response.ok || accept.includes(response.status)) {
      return response;
    }
    let message = response.statusText;
    try {
      message = (await response.json()).message ?? message;
    } catch {
    }
    throw new GithubError(`GitHub ${method} ${path.split("?")[0]} failed (HTTP ${response.status}): ${message}`, response.status);
  }
};

// src/models-ci/cli/runCli.ts
function apiFromEnv(env) {
  return new ApiClient({
    domain: requireEnv(env, "GRAVELMON_API_DOMAIN"),
    token: requireEnv(env, "POKEMON_STATUS_INTERNAL_TOKEN")
  });
}
function githubFromEnv(env) {
  return new GithubRest({
    repository: requireEnv(env, "GITHUB_REPOSITORY"),
    token: requireEnv(env, "GITHUB_TOKEN")
  });
}
async function runCli(main) {
  try {
    const result = await main(process.env, process.argv.slice(2));
    process.exitCode = result.exitCode;
  } catch (cause) {
    console.error(annotate("error", cause instanceof Error ? cause.message : String(cause)));
    process.exitCode = 1;
  }
}

// src/models-ci/cli/sync-credits.cli.ts
void runCli(
  (env) => runSyncCredits(syncInputFromEnv(env), {
    api: apiFromEnv(env),
    github: githubFromEnv(env),
    git: gitReader()
  })
);
