// GENERATED by gravelmon-submission-app/scripts/build-models-template.ts from src/models-ci/cli/tag-version.cli.ts.
// Do not edit: change the source and run `npm run build:models-template`.

// src/models-ci/github.ts
var GithubError = class extends Error {
  constructor(message, status) {
    super(message);
    this.status = status;
    this.name = "GithubError";
  }
};
function toPullRequestInfo(raw) {
  return {
    number: raw.number,
    body: raw.body ?? "",
    baseRef: raw.base.ref,
    headRef: raw.head.ref,
    merged: raw.merged === true || raw.merged_at !== void 0 && raw.merged_at !== null,
    authorLogin: raw.user?.login ?? "",
    authorType: raw.user?.type ?? "",
    ...raw.state === void 0 ? {} : { closed: raw.state === "closed" }
  };
}
var GithubRest = class {
  constructor(options) {
    this.repository = options.repository;
    this.token = options.token;
    this.fetchImpl = options.fetchImpl ?? ((url, init) => fetch(url, init));
    this.baseUrl = options.baseUrl ?? "https://api.github.com";
  }
  /** The pull requests GitHub associates with a commit (the lookup the credit sync always used). */
  async listPullRequestsAssociatedWithCommit(sha) {
    const response = await this.send("GET", `/commits/${encodeURIComponent(sha)}/pulls?per_page=100`);
    return (await response.json()).map(toPullRequestInfo);
  }
  async getPullRequest(number) {
    const response = await this.send("GET", `/pulls/${number}`);
    return toPullRequestInfo(await response.json());
  }
  /** A comment on a pull request (pull requests are issues for comments). */
  async comment(number, body) {
    await this.send("POST", `/issues/${number}/comments`, { body });
  }
  /** The commit a tag points at, or `undefined` when there is no such tag. Lightweight tags only. */
  async getTag(tag) {
    const response = await this.send("GET", `/git/ref/tags/${encodeURIComponent(tag)}`, void 0, [404]);
    if (response.status === 404) {
      return void 0;
    }
    const body = await response.json();
    return { sha: body.object.sha, type: body.object.type };
  }
  /** Creates `refs/tags/<tag>` at a commit. Fails (422) if it exists: a tag is never moved. */
  async createTag(tag, sha) {
    await this.send("POST", "/git/refs", { ref: `refs/tags/${tag}`, sha });
  }
  /**
   * Deletes `refs/heads/<branch>`. `missing` when there is no such branch (404, or 422 "Reference does
   * not exist"): the job is "make sure it is gone", so a branch that already is, is a success.
   */
  async deleteBranch(branch) {
    const path = `/git/refs/heads/${branch.split("/").map(encodeURIComponent).join("/")}`;
    const response = await this.send("DELETE", path, void 0, [404, 422]);
    return response.ok ? "deleted" : "missing";
  }
  async send(method, path, body, accept = []) {
    const response = await this.fetchImpl(`${this.baseUrl}/repos/${this.repository}${path}`, {
      method,
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${this.token}`,
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "gravelmon-models-ci",
        ...body === void 0 ? {} : { "Content-Type": "application/json" }
      },
      body: body === void 0 ? void 0 : JSON.stringify(body)
    });
    if (response.ok || accept.includes(response.status)) {
      return response;
    }
    let message = response.statusText;
    try {
      message = (await response.json()).message ?? message;
    } catch {
    }
    throw new GithubError(`GitHub ${method} ${path.split("?")[0]} failed (HTTP ${response.status}): ${message}`, response.status);
  }
};

// src/models-ci/pullRequests.ts
var MAIN_BRANCH = "main";
function isVersionBranch(name) {
  return /^\d+\.\d+\.\d+$/.test(name);
}
async function resolveMergedPullRequest(github, sha, baseRef) {
  const all = await github.listPullRequestsAssociatedWithCommit(sha);
  return all.find((pr) => pr.merged && (baseRef === void 0 || pr.baseRef === baseRef));
}

// src/gravelmon-species/sha256.ts
var K = new Uint32Array([
  1116352408,
  1899447441,
  3049323471,
  3921009573,
  961987163,
  1508970993,
  2453635748,
  2870763221,
  3624381080,
  310598401,
  607225278,
  1426881987,
  1925078388,
  2162078206,
  2614888103,
  3248222580,
  3835390401,
  4022224774,
  264347078,
  604807628,
  770255983,
  1249150122,
  1555081692,
  1996064986,
  2554220882,
  2821834349,
  2952996808,
  3210313671,
  3336571891,
  3584528711,
  113926993,
  338241895,
  666307205,
  773529912,
  1294757372,
  1396182291,
  1695183700,
  1986661051,
  2177026350,
  2456956037,
  2730485921,
  2820302411,
  3259730800,
  3345764771,
  3516065817,
  3600352804,
  4094571909,
  275423344,
  430227734,
  506948616,
  659060556,
  883997877,
  958139571,
  1322822218,
  1537002063,
  1747873779,
  1955562222,
  2024104815,
  2227730452,
  2361852424,
  2428436474,
  2756734187,
  3204031479,
  3329325298
]);

// src/gravelmon-species/speciesKeys.ts
var CATALOG_INDEX = "gsi-catalog";
var BULK_INDEX = "gsi-bulk";
var CHANGE_REQUEST_INDEX = "gsi-cr";
var CATALOG_PROJECTED_ATTRIBUTES = [
  "formId",
  "addedByGame",
  "source",
  "revision",
  "catalogue",
  "name",
  "primaryType",
  "secondaryType",
  "preEvolution",
  "abilities"
];
var SPECIES_TABLE_SCHEMA = {
  keySchema: [
    { AttributeName: "pk", KeyType: "HASH" },
    { AttributeName: "sk", KeyType: "RANGE" }
  ],
  attributeDefinitions: [
    { AttributeName: "pk", AttributeType: "S" },
    { AttributeName: "sk", AttributeType: "S" },
    { AttributeName: "cpk", AttributeType: "S" },
    { AttributeName: "csk", AttributeType: "S" },
    { AttributeName: "bpk", AttributeType: "S" },
    { AttributeName: "bsk", AttributeType: "S" },
    { AttributeName: "crpk", AttributeType: "S" },
    { AttributeName: "crsk", AttributeType: "S" }
  ],
  globalSecondaryIndexes: [
    {
      IndexName: CATALOG_INDEX,
      KeySchema: [
        { AttributeName: "cpk", KeyType: "HASH" },
        { AttributeName: "csk", KeyType: "RANGE" }
      ],
      Projection: {
        ProjectionType: "INCLUDE",
        NonKeyAttributes: [...CATALOG_PROJECTED_ATTRIBUTES]
      }
    },
    {
      IndexName: BULK_INDEX,
      KeySchema: [
        { AttributeName: "bpk", KeyType: "HASH" },
        { AttributeName: "bsk", KeyType: "RANGE" }
      ],
      Projection: { ProjectionType: "ALL" }
    },
    {
      IndexName: CHANGE_REQUEST_INDEX,
      KeySchema: [
        { AttributeName: "crpk", KeyType: "HASH" },
        { AttributeName: "crsk", KeyType: "RANGE" }
      ],
      Projection: { ProjectionType: "ALL" }
    }
  ]
};

// src/gravelmon-species/speciesItems.ts
var RESERVED_FIELDS = /* @__PURE__ */ new Set([
  "pk",
  "sk",
  "formId",
  "addedByGame",
  "source",
  "revision",
  "origin",
  "catalogue",
  "lang",
  "cpk",
  "csk",
  "bpk",
  "bsk"
]);
var IMMUTABLE_FIELDS = new Set(
  [...RESERVED_FIELDS].filter((name) => name !== "lang")
);

// src/gravelmon-species/speciesPatch.ts
var MAX_VALUE_BYTES = 64 * 1024;

// src/gravelmon-tags/tagCodec.ts
var MAX_TAG_JSON_BYTES = 128 * 1024;

// src/services/remote/rawFileClient.ts
var COBBLEMON_PROJECT_PATH = encodeURIComponent("cable-mc/cobblemon");

// src/models-ci/runtime.ts
var ConfigError = class extends Error {
};
function requireEnv(env, name) {
  const value = env[name];
  if (value === void 0 || value.trim() === "") {
    throw new ConfigError(`${name} is not set.`);
  }
  return value;
}
function optionalEnv(env, name) {
  const value = env[name];
  return value === void 0 || value.trim() === "" ? void 0 : value.trim();
}
function annotate(level, message) {
  const escaped = message.replace(/%/g, "%25").replace(/\r/g, "%0D").replace(/\n/g, "%0A");
  return `::${level}::${escaped}`;
}

// src/models-ci/validateTree.ts
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

// src/services/remote/aspectOrder.json
var aspectOrder_default = {
  alolan: 1,
  female: 2,
  galarian: 3,
  hisuian: 4,
  paldean: 5,
  valencian: 6,
  cosplay: 7,
  world: 8,
  gmax: 9,
  starter: 10,
  partner: 11,
  kalos: 12,
  unova: 13,
  sinnoh: 14,
  libre: 15,
  phd: 16,
  pop_star: 17,
  belle: 18,
  rock_star: 19,
  mega: 20,
  sunny: 21,
  rainy: 22,
  snowy: 23,
  hoennian: 24,
  x: 25,
  storm: 26,
  fairy: 27,
  dragon: 28,
  psychic: 29,
  sound: 30,
  water: 31,
  steel: 32,
  ground: 33,
  poison: 34,
  rock: 35,
  grass: 36,
  flying: 37,
  fighting: 38,
  electric: 39,
  dark: 40,
  ice: 41,
  ghost: 42,
  fire: 43,
  red: 44,
  green: 45,
  yellow: 46,
  monster: 47,
  summer: 48,
  school: 49,
  swarm: 50,
  dry: 51,
  sirius: 52,
  altair: 53,
  one: 54,
  two: 55,
  three: 56,
  four: 57,
  five: 58,
  six: 59,
  seven: 60,
  eight: 61,
  nine: 62,
  ten: 63,
  eleven: 64,
  twelve: 65,
  thirteen: 66,
  fourteen: 67,
  fifteen: 68,
  sixteen: 69,
  seventeen: 70,
  eighteen: 71,
  nineteen: 72,
  twenty: 73,
  twentyone: 74,
  twentytwo: 75,
  twentythree: 76,
  twentyfour: 77,
  twentyfive: 78,
  twentysix: 79,
  twentyseven: 80,
  nose_pattern: 81,
  brow_pattern: 82,
  qamoran: 83,
  nostan: 84,
  varitasian: 85,
  seviian: 86,
  deep: 87,
  ayreian: 88,
  kaskadian: 89,
  mystic: 90,
  avalossian: 91,
  enjinian: 92,
  novran: 93,
  neo: 94,
  norheiman: 95,
  avorian: 96,
  hizian: 97,
  alteran: 98,
  aristosian: 99,
  armiran: 100,
  relic: 101,
  gutsy: 102,
  windy: 103,
  smoggy: 104,
  dusty: 105,
  sandy: 106,
  swarmy: 107,
  spooky: 108,
  whirly: 109,
  allergy: 110,
  zappy: 111,
  zenny: 112,
  sorcery: 113,
  shady: 114,
  lovely: 115,
  cefiran: 116,
  egho: 117,
  delta: 118,
  spider: 119,
  ruin: 120,
  berry: 121,
  cake: 122,
  unleashed: 123,
  inactive: 124,
  crystal: 125,
  active: 126,
  blaze_boost: 127,
  armored: 128,
  magician: 129,
  blue: 130,
  exothermic: 131,
  hubian: 132,
  earth: 133,
  havaiiian: 134,
  lagoonan: 135,
  rican: 136,
  crozoican: 137,
  interian: 138,
  signetan: 139,
  okenian: 140,
  lost_islands: 141,
  space: 142,
  sage_space: 143,
  beta: 144,
  terrestrial: 145,
  xenoversal: 146,
  astral: 147,
  mix: 148,
  twirl: 149,
  bass: 150,
  home: 151,
  junk: 152,
  web: 153,
  brawl: 154,
  sway: 155,
  sol: 156,
  amaze_all: 157,
  eldiwan: 158,
  winter_coat: 159,
  summer_coat: 160,
  xenoverse: 161,
  africanusan: 162,
  vesitan: 163,
  epoch: 164,
  tokassian: 165,
  pastelian: 166,
  nodorran: 167,
  olysosian: 168,
  ottoran: 169,
  mystisian: 170,
  mastenian: 171,
  theossian: 172,
  dhioman: 173,
  ionosian: 174,
  forman: 175,
  raianian: 176,
  tribal: 177,
  norse: 178,
  palmian: 179,
  trizoran: 180,
  forest: 181,
  cave: 182,
  sea: 183,
  ivrisian: 184,
  ferranian: 185,
  mahalian: 186,
  fabelian: 187,
  sahlian: 188,
  elbian: 189,
  aromian: 190,
  mikitarian: 191,
  ishirian: 192,
  shadow: 193,
  guitarist: 194,
  drummer: 195,
  bassist: 196,
  nuclear: 197
};

// src/services/remote/gravelmonPaths.ts
var ASPECT_ORDER = aspectOrder_default;
var ASPECT_BY_ORDINAL = new Map(
  Object.entries(ASPECT_ORDER).map(([aspect, order]) => [order, aspect])
);

// src/gravelmon-models/formFolder.ts
var FORM_FOLDER_CREDITS_FILE = "credits.json";
var FORM_FOLDER_INSTALL_FILE = "install.json";
var MISMATCHED_FOLDER = ".mismatched";
function isMismatchedPath(path) {
  return path.split("/").includes(MISMATCHED_FOLDER);
}
function isValidFolderSegment(segment) {
  return /^[A-Za-z0-9][A-Za-z0-9_.-]*$/.test(segment) && !segment.endsWith(".") && segment !== "..";
}
function parseFormFolderPath(path) {
  const segments = path.split("/");
  if (segments.length !== 2 || !segments.every(isValidFolderSegment)) {
    return void 0;
  }
  return { game: segments[0], folder: segments[1] };
}

// src/gravelmon-models/installManifest.ts
var RESERVED_FILE_NAMES = [
  FORM_FOLDER_INSTALL_FILE,
  FORM_FOLDER_CREDITS_FILE
];
var PACK_ROOT = "assets/";
var FORBIDDEN_NAME_CHARACTERS = /[\\/:*?"<>|\u0000-\u001f]/;
function isValidFlatName(name) {
  return name.length > 0 && name.length <= 200 && name !== "." && name !== ".." && !FORBIDDEN_NAME_CHARACTERS.test(name) && !name.endsWith(".") && !name.endsWith(" ");
}
function isValidInstallPath(path) {
  if (!path.startsWith(PACK_ROOT) || path.includes("\\") || path.includes(":")) {
    return false;
  }
  const segments = path.split("/");
  return segments.length >= 3 && segments.every((s) => s !== "" && s !== "." && s !== "..");
}
function parseUsesEntry(entry) {
  const segments = entry.split("/");
  if (segments.length !== 3) {
    return void 0;
  }
  const [game, folder, file] = segments;
  return isValidFolderSegment(game) && isValidFolderSegment(folder) && isValidFlatName(file) ? { game, folder, file } : void 0;
}
function validateInstallManifest(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return [{ code: "not_an_object", message: "install.json must be a JSON object." }];
  }
  const issues = [];
  const record = value;
  for (const key of Object.keys(record)) {
    if (key !== "files" && key !== "uses") {
      issues.push({ code: "unknown_key", message: `Unknown key "${key}".` });
    }
  }
  const files = record.files;
  if (typeof files !== "object" || files === null || Array.isArray(files)) {
    issues.push({ code: "files_missing", message: '"files" must be an object.' });
  } else {
    issues.push(...validateFiles(files));
  }
  if (record.uses !== void 0) {
    issues.push(...validateUses(record.uses));
  }
  return issues;
}
function validateFiles(files) {
  const issues = [];
  const entries = Object.entries(files);
  if (entries.length === 0) {
    issues.push({ code: "files_empty", message: '"files" lists no file.' });
  }
  const seenNames = /* @__PURE__ */ new Map();
  const seenPaths = /* @__PURE__ */ new Map();
  for (const [name, installPath] of entries) {
    if (!isValidFlatName(name)) {
      issues.push({ code: "bad_flat_name", message: `"${name}" is not a plain file name.` });
    }
    const lowered = name.toLowerCase();
    if (RESERVED_FILE_NAMES.includes(lowered)) {
      issues.push({ code: "reserved_name", message: `"${name}" is a reserved file name.` });
    }
    const clash = seenNames.get(lowered);
    if (clash !== void 0) {
      issues.push({
        code: "duplicate_flat_name",
        message: `"${name}" and "${clash}" differ only by case.`
      });
    }
    seenNames.set(lowered, name);
    if (typeof installPath !== "string" || !isValidInstallPath(installPath)) {
      issues.push({
        code: "bad_install_path",
        message: `"${name}" installs to ${JSON.stringify(installPath)}, which is not a valid path under assets/.`
      });
      continue;
    }
    const same = seenPaths.get(installPath);
    if (same !== void 0) {
      issues.push({
        code: "duplicate_install_path",
        message: `"${name}" and "${same}" both install to ${installPath}.`
      });
    }
    seenPaths.set(installPath, name);
  }
  return issues;
}
function validateUses(uses) {
  if (!Array.isArray(uses)) {
    return [{ code: "bad_uses", message: '"uses" must be an array.' }];
  }
  const issues = [];
  const seen = /* @__PURE__ */ new Set();
  for (const entry of uses) {
    if (typeof entry !== "string" || parseUsesEntry(entry) === void 0) {
      issues.push({
        code: "bad_uses",
        message: `${JSON.stringify(entry)} is not a <game>/<folder>/<file> path.`
      });
    } else if (seen.has(entry)) {
      issues.push({ code: "bad_uses", message: `"${entry}" is listed twice in "uses".` });
    }
    if (typeof entry === "string") {
      seen.add(entry);
    }
  }
  return issues;
}
function validateModelsTree(folders) {
  const issues = [];
  const sound = /* @__PURE__ */ new Map();
  const installOwners = /* @__PURE__ */ new Map();
  for (const folder of folders) {
    if (isMismatchedPath(folder.path)) {
      continue;
    }
    if (parseFormFolderPath(folder.path) === void 0) {
      issues.push({
        code: "bad_folder_path",
        folder: folder.path,
        message: "A form folder must be <game>/<name>."
      });
    }
    if (folder.manifest === void 0) {
      issues.push({
        code: "manifest_missing",
        folder: folder.path,
        message: "No install.json."
      });
      continue;
    }
    const manifestIssues = validateInstallManifest(folder.manifest);
    for (const issue of manifestIssues) {
      issues.push({
        code: "manifest_invalid",
        folder: folder.path,
        message: `${issue.code}: ${issue.message}`
      });
    }
    if (manifestIssues.length > 0) {
      continue;
    }
    const manifest = folder.manifest;
    sound.set(folder.path, manifest);
    issues.push(...checkFolderFiles(folder, manifest));
    for (const [name, installPath] of Object.entries(manifest.files)) {
      const owner = installOwners.get(installPath);
      if (owner !== void 0 && owner !== folder.path) {
        issues.push({
          code: "install_path_collision",
          folder: folder.path,
          message: `${name} installs to ${installPath}, which ${owner} also installs.`
        });
      }
      installOwners.set(installPath, owner ?? folder.path);
    }
  }
  for (const [path, manifest] of sound) {
    for (const entry of manifest.uses ?? []) {
      const target = parseUsesEntry(entry);
      if (target === void 0) {
        continue;
      }
      if (`${target.game}/${target.folder}` === path) {
        issues.push({
          code: "uses_self",
          folder: path,
          message: `uses ${entry}, which is its own file.`
        });
      } else if (sound.get(`${target.game}/${target.folder}`)?.files[target.file] === void 0) {
        issues.push({
          code: "uses_missing",
          folder: path,
          message: `uses ${entry}, which does not exist.`
        });
      }
    }
  }
  return issues;
}
function checkFolderFiles(folder, manifest) {
  const issues = [];
  const payload = /* @__PURE__ */ new Set();
  for (const file of folder.files) {
    if (file.includes("/")) {
      issues.push({
        code: "nested_file",
        folder: folder.path,
        message: `${file} is nested; form folders are flat.`
      });
    } else if (!RESERVED_FILE_NAMES.includes(file)) {
      payload.add(file);
    }
  }
  for (const file of payload) {
    if (manifest.files[file] === void 0) {
      issues.push({
        code: "file_without_entry",
        folder: folder.path,
        message: `${file} has no entry in install.json.`
      });
    }
  }
  for (const name of Object.keys(manifest.files)) {
    if (!payload.has(name)) {
      issues.push({
        code: "entry_without_file",
        folder: folder.path,
        message: `install.json lists ${name}, which is not in the folder.`
      });
    }
  }
  return issues;
}

// src/models-ci/validateTree.ts
var NON_GAME_ROOTS = [".git", ".github", "scripts", "node_modules", "_unreferenced"];
var ALLOWED_ROOT_FILES = [
  "VERSION",
  "MIGRATION.md",
  "README.md",
  "LICENSE",
  ".gitattributes",
  ".gitignore"
];
function walk(directory, prefix = "") {
  const files = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const relative = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      files.push(...walk(join(directory, entry.name), relative));
    } else {
      files.push(relative);
    }
  }
  return files.sort();
}
function readModelsTree(root) {
  const folders = [];
  const parseIssues = [];
  const warnings = [];
  for (const top of readdirSync(root, { withFileTypes: true })) {
    if (!top.isDirectory()) {
      if (!ALLOWED_ROOT_FILES.includes(top.name)) {
        warnings.push(`${top.name} at the repository root is not part of the layout.`);
      }
      continue;
    }
    if (NON_GAME_ROOTS.includes(top.name)) {
      continue;
    }
    for (const entry of readdirSync(join(root, top.name), { withFileTypes: true })) {
      const path = `${top.name}/${entry.name}`;
      if (entry.name === MISMATCHED_FOLDER) {
        continue;
      }
      if (!entry.isDirectory()) {
        warnings.push(`${path} is a file directly inside a game folder; form folders are <game>/<name>/.`);
        continue;
      }
      const directory = join(root, top.name, entry.name);
      const files = walk(directory);
      let manifest;
      if (files.includes(FORM_FOLDER_INSTALL_FILE)) {
        try {
          manifest = JSON.parse(readFileSync(join(directory, FORM_FOLDER_INSTALL_FILE), "utf8"));
        } catch (cause) {
          manifest = null;
          parseIssues.push({
            code: "manifest_invalid",
            folder: path,
            message: `install.json is not valid JSON: ${cause instanceof Error ? cause.message : String(cause)}`
          });
        }
      }
      folders.push({ path, files, manifest });
    }
  }
  folders.sort((a, b) => a.path < b.path ? -1 : 1);
  return { folders, parseIssues, warnings };
}
function validateTreeAt(root, expectedVersion) {
  const { folders, parseIssues, warnings } = readModelsTree(root);
  const unparsable = new Set(parseIssues.map((issue) => issue.folder));
  const issues = [
    ...parseIssues,
    ...validateModelsTree(folders).filter((issue) => !unparsable.has(issue.folder))
  ];
  if (expectedVersion !== void 0) {
    const versionFile = join(root, "VERSION");
    if (!existsSync(versionFile)) {
      warnings.push("There is no VERSION file at the root.");
    } else if (readFileSync(versionFile, "utf8").trim() !== expectedVersion) {
      warnings.push(
        `VERSION says "${readFileSync(versionFile, "utf8").trim()}" but this release is ${expectedVersion}.`
      );
    }
  }
  return { folders: folders.length, issues, warnings };
}
var MAX_PRINTED = 50;
function reportTree(report, log) {
  for (const warning of report.warnings) {
    log(annotate("warning", warning));
  }
  for (const issue of report.issues.slice(0, MAX_PRINTED)) {
    log(annotate("error", `${issue.folder}: [${issue.code}] ${issue.message}`));
  }
  if (report.issues.length > MAX_PRINTED) {
    log(annotate("error", `... and ${report.issues.length - MAX_PRINTED} more issues.`));
  }
  if (report.issues.length === 0) {
    log(`The tree is valid: ${report.folders} form folders.`);
    return { exitCode: 0 };
  }
  return { exitCode: 1 };
}

// src/models-ci/tagVersion.ts
async function runTagVersion(input, deps) {
  const log = deps.log ?? ((message) => console.log(message));
  const version = await resolveVersion(input, deps, log);
  if (version === void 0) {
    return { exitCode: 0 };
  }
  const tag = `v${version}`;
  const report = (deps.validateTree ?? validateTreeAt)(input.root, version);
  if (reportTree(report, log).exitCode !== 0) {
    log(annotate("error", `The tree does not pass its checks, so ${tag} was not created.`));
    return { exitCode: 1 };
  }
  const outcome = await ensureTag(deps.github, tag, input.sha);
  if (outcome.status === "elsewhere") {
    log(
      annotate(
        "error",
        `${tag} already exists on ${outcome.sha}, not on ${input.sha}. A tag never moves; pick a new version or delete the tag by hand if it was made by mistake.`
      )
    );
    return { exitCode: 1 };
  }
  log(outcome.status === "created" ? `Created ${tag} on ${input.sha}.` : `${tag} is already on ${input.sha}.`);
  const answer = await deps.api.post("/api/internal/publish", { version, tag }, "any");
  if (answer.outcome !== "published" && answer.outcome !== "already_published") {
    log(annotate("error", `The API answered "${answer.outcome}" to publish ${tag}.`));
    return { exitCode: 1 };
  }
  log(`Recorded ${tag} as published (${answer.outcome}).`);
  return { exitCode: 0 };
}
async function resolveVersion(input, deps, log) {
  if (input.eventName === "workflow_dispatch") {
    const version = input.version?.trim() ?? "";
    if (!isVersionBranch(version)) {
      throw new ConfigError(`version must look like 4.0.1, not "${version}".`);
    }
    if (input.ref !== `refs/heads/${MAIN_BRANCH}`) {
      throw new ConfigError(`Run this workflow on ${MAIN_BRANCH}: it tags the commit it runs on (this is ${input.ref}).`);
    }
    return version;
  }
  const pr = await resolveMergedPullRequest(deps.github, input.sha, MAIN_BRANCH);
  if (pr === void 0 || !isVersionBranch(pr.headRef)) {
    log(`Not a version-branch merge (${pr?.headRef ?? "no merged PR"}); no tag.`);
    return void 0;
  }
  log(`Releasing version branch ${pr.headRef}.`);
  return pr.headRef;
}
async function ensureTag(github, tag, sha) {
  const existing = await github.getTag(tag);
  if (existing !== void 0) {
    return existing.sha === sha && existing.type === "commit" ? { status: "exists" } : { status: "elsewhere", sha: existing.sha };
  }
  try {
    await github.createTag(tag, sha);
    return { status: "created" };
  } catch (cause) {
    if (cause instanceof GithubError && cause.status === 422) {
      const winner = await github.getTag(tag);
      if (winner !== void 0) {
        return winner.sha === sha && winner.type === "commit" ? { status: "exists" } : { status: "elsewhere", sha: winner.sha };
      }
    }
    throw cause;
  }
}
function tagVersionInputFromEnv(env, root) {
  return {
    eventName: requireEnv(env, "GITHUB_EVENT_NAME"),
    ref: requireEnv(env, "GITHUB_REF"),
    sha: requireEnv(env, "GITHUB_SHA"),
    version: optionalEnv(env, "VERSION_INPUT"),
    root
  };
}

// src/models-ci/apiClient.ts
import { createHash } from "node:crypto";
var ApiError = class extends Error {
  constructor(message, path, status, ambiguous, responseText) {
    super(message);
    this.path = path;
    this.status = status;
    this.ambiguous = ambiguous;
    this.responseText = responseText;
    this.name = "ApiError";
  }
};
var DEFAULT_MAX_ATTEMPTS = 5;
var DEFAULT_BASE_DELAY_MS = 2e3;
var MAX_DELAY_MS = 6e4;
function sha256Hex(value) {
  return createHash("sha256").update(value, "utf8").digest("hex");
}
function retryable(policy, status) {
  if (policy === "never") {
    return false;
  }
  if (policy === "any") {
    return status === void 0 || status === 429 || status >= 500;
  }
  return status === 429 || status === 503;
}
var ApiClient = class {
  constructor(options) {
    this.domain = options.domain.replace(/\/+$/, "");
    this.token = options.token;
    this.fetchImpl = options.fetchImpl ?? ((url, init) => fetch(url, init));
    this.sleep = options.sleep ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));
    this.random = options.random ?? Math.random;
    this.maxAttempts = options.maxAttempts ?? DEFAULT_MAX_ATTEMPTS;
    this.baseDelayMs = options.baseDelayMs ?? DEFAULT_BASE_DELAY_MS;
    this.log = options.log ?? ((message) => console.log(message));
  }
  /** POSTs JSON and returns the parsed answer. Throws {@link ApiError} for anything but a 2xx JSON answer. */
  async post(path, body, retry) {
    const jsonBody = JSON.stringify(body);
    const attempts = retry === "never" ? 1 : this.maxAttempts;
    for (let attempt = 1; ; attempt++) {
      let status;
      let text;
      let retryAfterMs;
      let failure;
      try {
        const response = await this.fetchImpl(`${this.domain}${path}`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-Gravelmon-Token": `Bearer ${this.token}`,
            "x-amz-content-sha256": sha256Hex(jsonBody)
          },
          body: jsonBody
        });
        status = response.status;
        text = await response.text();
        const retryAfter = Number(response.headers.get("retry-after"));
        retryAfterMs = Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1e3 : void 0;
        if (response.ok) {
          this.log(`${path} -> ${status}: ${text}`);
          return parseJson(path, status, text);
        }
        failure = `${path} -> ${status}: ${text}`;
      } catch (cause) {
        if (cause instanceof ApiError) {
          throw cause;
        }
        failure = `${path} failed: ${cause instanceof Error ? cause.message : String(cause)}`;
      }
      if (!retryable(retry, status) || attempt >= attempts) {
        const ambiguous = retry !== "any" && (status === void 0 || status >= 500 && status !== 503);
        throw new ApiError(
          ambiguous ? `${failure} (ambiguous: the write may have landed)` : failure,
          path,
          status,
          ambiguous,
          text
        );
      }
      const delay = Math.min(
        Math.max(this.baseDelayMs * 2 ** (attempt - 1) + this.random() * 1e3, retryAfterMs ?? 0),
        MAX_DELAY_MS
      );
      this.log(`${path} attempt ${attempt}/${attempts} failed (${failure}); retrying in ${Math.round(delay)}ms.`);
      await this.sleep(delay);
    }
  }
};
function parseJson(path, status, text) {
  try {
    return JSON.parse(text);
  } catch {
    throw new ApiError(`${path} -> ${status}: the answer is not JSON: ${text.slice(0, 200)}`, path, status, false, text);
  }
}

// src/models-ci/cli/runCli.ts
function apiFromEnv(env) {
  return new ApiClient({
    domain: requireEnv(env, "GRAVELMON_API_DOMAIN"),
    token: requireEnv(env, "POKEMON_STATUS_INTERNAL_TOKEN")
  });
}
function githubFromEnv(env) {
  return new GithubRest({
    repository: requireEnv(env, "GITHUB_REPOSITORY"),
    token: requireEnv(env, "GITHUB_TOKEN")
  });
}
async function runCli(main) {
  try {
    const result = await main(process.env, process.argv.slice(2));
    process.exitCode = result.exitCode;
  } catch (cause) {
    console.error(annotate("error", cause instanceof Error ? cause.message : String(cause)));
    process.exitCode = 1;
  }
}

// src/models-ci/cli/tag-version.cli.ts
void runCli(
  (env, args) => runTagVersion(tagVersionInputFromEnv(env, args[0] ?? "."), { api: apiFromEnv(env), github: githubFromEnv(env) })
);
