// GENERATED by gravelmon-submission-app/scripts/build-models-template.ts from src/models-ci/cli/validate-data.cli.ts.
// Do not edit: change the source and run `npm run build:models-template`.

// src/models-ci/validateData.ts
import { readFileSync } from "node:fs";

// src/models-ci/apiClient.ts
import { createHash } from "node:crypto";
var ApiError = class extends Error {
  constructor(message, path, status, ambiguous, responseText) {
    super(message);
    this.path = path;
    this.status = status;
    this.ambiguous = ambiguous;
    this.responseText = responseText;
    this.name = "ApiError";
  }
};
var DEFAULT_MAX_ATTEMPTS = 5;
var DEFAULT_BASE_DELAY_MS = 2e3;
var MAX_DELAY_MS = 6e4;
function sha256Hex(value) {
  return createHash("sha256").update(value, "utf8").digest("hex");
}
function retryable(policy, status) {
  if (policy === "never") {
    return false;
  }
  if (policy === "any") {
    return status === void 0 || status === 429 || status >= 500;
  }
  return status === 429 || status === 503;
}
var ApiClient = class {
  constructor(options) {
    this.domain = options.domain.replace(/\/+$/, "");
    this.token = options.token;
    this.fetchImpl = options.fetchImpl ?? ((url, init) => fetch(url, init));
    this.sleep = options.sleep ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));
    this.random = options.random ?? Math.random;
    this.maxAttempts = options.maxAttempts ?? DEFAULT_MAX_ATTEMPTS;
    this.baseDelayMs = options.baseDelayMs ?? DEFAULT_BASE_DELAY_MS;
    this.log = options.log ?? ((message) => console.log(message));
  }
  /** POSTs JSON and returns the parsed answer. Throws {@link ApiError} for anything but a 2xx JSON answer. */
  async post(path, body, retry) {
    const jsonBody = JSON.stringify(body);
    const attempts = retry === "never" ? 1 : this.maxAttempts;
    for (let attempt = 1; ; attempt++) {
      let status;
      let text;
      let retryAfterMs;
      let failure;
      try {
        const response = await this.fetchImpl(`${this.domain}${path}`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-Gravelmon-Token": `Bearer ${this.token}`,
            "x-amz-content-sha256": sha256Hex(jsonBody)
          },
          body: jsonBody
        });
        status = response.status;
        text = await response.text();
        const retryAfter = Number(response.headers.get("retry-after"));
        retryAfterMs = Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1e3 : void 0;
        if (response.ok) {
          this.log(`${path} -> ${status}: ${text}`);
          return parseJson(path, status, text);
        }
        failure = `${path} -> ${status}: ${text}`;
      } catch (cause) {
        if (cause instanceof ApiError) {
          throw cause;
        }
        failure = `${path} failed: ${cause instanceof Error ? cause.message : String(cause)}`;
      }
      if (!retryable(retry, status) || attempt >= attempts) {
        const ambiguous = retry !== "any" && (status === void 0 || status >= 500 && status !== 503);
        throw new ApiError(
          ambiguous ? `${failure} (ambiguous: the write may have landed)` : failure,
          path,
          status,
          ambiguous,
          text
        );
      }
      const delay = Math.min(
        Math.max(this.baseDelayMs * 2 ** (attempt - 1) + this.random() * 1e3, retryAfterMs ?? 0),
        MAX_DELAY_MS
      );
      this.log(`${path} attempt ${attempt}/${attempts} failed (${failure}); retrying in ${Math.round(delay)}ms.`);
      await this.sleep(delay);
    }
  }
};
function parseJson(path, status, text) {
  try {
    return JSON.parse(text);
  } catch {
    throw new ApiError(`${path} -> ${status}: the answer is not JSON: ${text.slice(0, 200)}`, path, status, false, text);
  }
}

// src/models-ci/pullRequests.ts
function isAppOpened(pr, appLogin) {
  if (appLogin === void 0 || appLogin.trim() === "") {
    return false;
  }
  return pr.authorType === "Bot" && pr.authorLogin.toLowerCase() === appLogin.trim().toLowerCase();
}

// src/gravelmon-species/sha256.ts
var K = new Uint32Array([
  1116352408,
  1899447441,
  3049323471,
  3921009573,
  961987163,
  1508970993,
  2453635748,
  2870763221,
  3624381080,
  310598401,
  607225278,
  1426881987,
  1925078388,
  2162078206,
  2614888103,
  3248222580,
  3835390401,
  4022224774,
  264347078,
  604807628,
  770255983,
  1249150122,
  1555081692,
  1996064986,
  2554220882,
  2821834349,
  2952996808,
  3210313671,
  3336571891,
  3584528711,
  113926993,
  338241895,
  666307205,
  773529912,
  1294757372,
  1396182291,
  1695183700,
  1986661051,
  2177026350,
  2456956037,
  2730485921,
  2820302411,
  3259730800,
  3345764771,
  3516065817,
  3600352804,
  4094571909,
  275423344,
  430227734,
  506948616,
  659060556,
  883997877,
  958139571,
  1322822218,
  1537002063,
  1747873779,
  1955562222,
  2024104815,
  2227730452,
  2361852424,
  2428436474,
  2756734187,
  3204031479,
  3329325298
]);

// src/gravelmon-species/speciesKeys.ts
var CATALOG_INDEX = "gsi-catalog";
var BULK_INDEX = "gsi-bulk";
var CHANGE_REQUEST_INDEX = "gsi-cr";
var CATALOG_PROJECTED_ATTRIBUTES = [
  "formId",
  "addedByGame",
  "source",
  "revision",
  "catalogue",
  "name",
  "primaryType",
  "secondaryType",
  "preEvolution",
  "abilities"
];
var SPECIES_TABLE_SCHEMA = {
  keySchema: [
    { AttributeName: "pk", KeyType: "HASH" },
    { AttributeName: "sk", KeyType: "RANGE" }
  ],
  attributeDefinitions: [
    { AttributeName: "pk", AttributeType: "S" },
    { AttributeName: "sk", AttributeType: "S" },
    { AttributeName: "cpk", AttributeType: "S" },
    { AttributeName: "csk", AttributeType: "S" },
    { AttributeName: "bpk", AttributeType: "S" },
    { AttributeName: "bsk", AttributeType: "S" },
    { AttributeName: "crpk", AttributeType: "S" },
    { AttributeName: "crsk", AttributeType: "S" }
  ],
  globalSecondaryIndexes: [
    {
      IndexName: CATALOG_INDEX,
      KeySchema: [
        { AttributeName: "cpk", KeyType: "HASH" },
        { AttributeName: "csk", KeyType: "RANGE" }
      ],
      Projection: {
        ProjectionType: "INCLUDE",
        NonKeyAttributes: [...CATALOG_PROJECTED_ATTRIBUTES]
      }
    },
    {
      IndexName: BULK_INDEX,
      KeySchema: [
        { AttributeName: "bpk", KeyType: "HASH" },
        { AttributeName: "bsk", KeyType: "RANGE" }
      ],
      Projection: { ProjectionType: "ALL" }
    },
    {
      IndexName: CHANGE_REQUEST_INDEX,
      KeySchema: [
        { AttributeName: "crpk", KeyType: "HASH" },
        { AttributeName: "crsk", KeyType: "RANGE" }
      ],
      Projection: { ProjectionType: "ALL" }
    }
  ]
};

// src/gravelmon-species/speciesItems.ts
var RESERVED_FIELDS = /* @__PURE__ */ new Set([
  "pk",
  "sk",
  "formId",
  "addedByGame",
  "source",
  "revision",
  "origin",
  "catalogue",
  "lang",
  "cpk",
  "csk",
  "bpk",
  "bsk"
]);
var IMMUTABLE_FIELDS = new Set(
  [...RESERVED_FIELDS].filter((name) => name !== "lang")
);
function canonicalJson(value) {
  return JSON.stringify(sortKeys(value));
}
function sortKeys(value) {
  if (Array.isArray(value)) {
    return value.map(sortKeys);
  }
  if (value !== null && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).filter(([, v]) => v !== void 0).sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0).map(([key, v]) => [key, sortKeys(v)])
    );
  }
  return value;
}
function jsonEqual(a, b) {
  return canonicalJson(a) === canonicalJson(b);
}

// src/gravelmon-species/speciesPatch.ts
var ADDITION_EDITABLE_FIELDS = [
  "features",
  "evolutions",
  "drops",
  "preEvolution"
];
var MAX_OPS_PER_CHANGE = 40;
var MAX_PATH_DEPTH = 6;
var MAX_LIST_EDIT_VALUES = 200;
var MAX_VALUE_BYTES = 64 * 1024;
var MODEL_TAG_SET_PATHS = ["baseScale", "hitbox"];
var MODEL_TAG_REMOVABLE = {
  labels: ["not_modeled"]
};
var CHANGE_REQUEST_EDITABLE_FIELDS = [
  "primaryType",
  "secondaryType",
  "catchRate",
  "maleRatio",
  "baseExperienceYield",
  "experienceGroup",
  "eggCycles",
  "baseFriendship",
  "baseScale",
  "cannotDynamax",
  "abilities",
  "behaviour",
  "baseStats",
  "evYield",
  "eggGroups",
  "drops",
  "moves",
  "placeholderMoves",
  "labels",
  "pokedex",
  "height",
  "weight",
  "evolutions",
  "preEvolution",
  "shoulderMountable",
  "hitbox",
  "features",
  "battleOnly",
  "lang",
  "rebalanced"
];
var SEGMENT = /^[A-Za-z][A-Za-z0-9_]*$/;
var FORBIDDEN_SEGMENTS = /* @__PURE__ */ new Set(["__proto__", "constructor", "prototype"]);
var LANG_KEY = /^[A-Za-z0-9_-]+(\.[A-Za-z0-9_-]+)*$/;
function parsePath(path) {
  if (path.startsWith("lang.")) {
    const key = path.slice("lang.".length);
    return LANG_KEY.test(key) && key.length <= 120 ? ["lang", key] : void 0;
  }
  const segments = path.split(".");
  if (segments.length === 0 || segments.length > MAX_PATH_DEPTH || !segments.every((s) => SEGMENT.test(s) && !FORBIDDEN_SEGMENTS.has(s))) {
    return void 0;
  }
  return segments;
}
function isSetOp(op) {
  return "to" in op;
}
function isAddOp(op) {
  return "add" in op;
}
function isRemoveOp(op) {
  return "remove" in op;
}
function isListEditOp(op) {
  return "edit" in op;
}
function isPlainObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function isFiniteNumber(value) {
  return typeof value === "number" && Number.isFinite(value);
}
function validateChange(change, kind, target = "species") {
  const problems = [];
  if (typeof change.formId !== "string" || change.formId === "") {
    problems.push("formId must be a non empty string.");
  }
  if (!Array.isArray(change.ops) || change.ops.length === 0) {
    problems.push("A change needs at least one op.");
    return problems;
  }
  if (change.ops.length > MAX_OPS_PER_CHANGE) {
    problems.push(`A change may hold at most ${MAX_OPS_PER_CHANGE} ops.`);
    return problems;
  }
  const seen = [];
  for (const [at, op] of change.ops.entries()) {
    const where = `ops[${at}]`;
    if (!isPlainObject(op) || typeof op.path !== "string") {
      problems.push(`${where}: an op needs a path.`);
      continue;
    }
    const segments = parsePath(op.path);
    if (segments === void 0) {
      problems.push(`${where}: "${op.path}" is not a valid path.`);
      continue;
    }
    const forms = ["to", "add", "remove", "edit"].filter((key) => key in op);
    if (forms.length !== 1) {
      problems.push(`${where}: an op has exactly one of to, add, remove or edit.`);
      continue;
    }
    if (target === "species" && IMMUTABLE_FIELDS.has(segments[0])) {
      problems.push(`${where}: "${segments[0]}" is not a species field and cannot change.`);
      continue;
    }
    if (isListEditOp(op)) {
      const editProblem = listEditProblem(op.edit);
      if (editProblem !== void 0) {
        problems.push(`${where}: ${editProblem}`);
        continue;
      }
    }
    const value = isSetOp(op) ? op.to : isAddOp(op) ? op.add : isListEditOp(op) ? op.edit : op.remove;
    if (value === void 0) {
      problems.push(`${where}: the value must be defined.`);
      continue;
    }
    if (JSON.stringify(value).length > MAX_VALUE_BYTES) {
      problems.push(`${where}: the value is larger than ${MAX_VALUE_BYTES} bytes.`);
      continue;
    }
    const clash = seen.find(
      (other) => other.length <= segments.length ? other.every((s, i) => s === segments[i]) : segments.every((s, i) => s === other[i])
    );
    if (clash !== void 0) {
      problems.push(`${where}: "${op.path}" overlaps another op's path.`);
      continue;
    }
    seen.push(segments);
    const refusal = kind === "model" ? target === "addition" ? "a model tag cannot change an addition." : modelTagRefusal(op) : requestRefusal(segments, target);
    if (refusal !== void 0) {
      problems.push(`${where}: ${refusal}`);
    }
  }
  return problems;
}
function listEditProblem(edit) {
  if (!isPlainObject(edit) || Object.keys(edit).some((key) => key !== "add" && key !== "remove")) {
    return "edit must be { add?, remove? }.";
  }
  const add = edit.add ?? [];
  const remove = edit.remove ?? [];
  if (!Array.isArray(add) || !Array.isArray(remove) || add.length + remove.length === 0) {
    return "edit needs lists of values to add or remove.";
  }
  if (add.length + remove.length > MAX_LIST_EDIT_VALUES) {
    return `edit may name at most ${MAX_LIST_EDIT_VALUES} values.`;
  }
  if (add.some((value) => remove.some((other) => jsonEqual(value, other)))) {
    return "edit adds and removes the same value.";
  }
  return void 0;
}
function modelTagRefusal(op) {
  if (isSetOp(op)) {
    if (!MODEL_TAG_SET_PATHS.includes(op.path)) {
      return `a model tag may only set ${MODEL_TAG_SET_PATHS.join(" or ")}, not "${op.path}".`;
    }
    if (op.path === "baseScale" && !(isFiniteNumber(op.to) && op.to > 0)) {
      return "baseScale must be a number above 0.";
    }
    if (op.path === "hitbox") {
      const box = op.to;
      const valid = isPlainObject(box) && isFiniteNumber(box.width) && box.width > 0 && isFiniteNumber(box.height) && box.height > 0 && (box.fixed === void 0 || typeof box.fixed === "boolean") && Object.keys(box).every((key) => ["width", "height", "fixed"].includes(key));
      if (!valid) {
        return "hitbox must be { width, height, fixed? } with positive numbers.";
      }
    }
    return void 0;
  }
  if (isRemoveOp(op)) {
    const allowed = MODEL_TAG_REMOVABLE[op.path];
    if (allowed === void 0 || !allowed.includes(op.remove)) {
      return "a model tag may only remove the not_modeled label.";
    }
    return void 0;
  }
  return "a model tag cannot add to a list.";
}
function requestRefusal(segments, target) {
  if (target === "addition") {
    return segments[0] === "additions" && segments.length >= 2 && ADDITION_EDITABLE_FIELDS.includes(segments[1]) ? void 0 : `"${segments.join(".")}" is not an editable field of an addition.`;
  }
  return CHANGE_REQUEST_EDITABLE_FIELDS.includes(segments[0]) ? void 0 : `"${segments[0]}" is not an editable field.`;
}

// src/gravelmon-tags/tagCodec.ts
var TAG_VERSION = 1;
var MARKERS = {
  data: "gravelmon-data",
  notes: "gravelmon-notes"
};
var MAX_TAG_PAYLOAD_CHARS = 24e3;
var MAX_TAG_JSON_BYTES = 128 * 1024;
var TagError = class extends Error {
  constructor(code, message) {
    super(message);
    this.code = code;
    this.name = "TagError";
  }
};
function fromBase64Url(text) {
  if (!/^[A-Za-z0-9_-]*$/.test(text) || text.length % 4 === 1) {
    throw new TagError("bad_encoding", "The tag is not valid base64url.");
  }
  const padded = text.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - text.length % 4) % 4);
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let at = 0; at < binary.length; at++) {
    bytes[at] = binary.charCodeAt(at);
  }
  return bytes;
}
async function gunzip(bytes, limit) {
  const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"));
  const reader = stream.getReader();
  const chunks = [];
  let total = 0;
  try {
    for (; ; ) {
      const { done, value } = await reader.read();
      if (done) {
        break;
      }
      total += value.length;
      if (total > limit) {
        await reader.cancel();
        throw new TagError("too_large", `The tag holds more than ${limit} bytes of JSON.`);
      }
      chunks.push(value);
    }
  } catch (cause) {
    if (cause instanceof TagError) {
      throw cause;
    }
    throw new TagError("bad_payload", "The tag is not gzip data.");
  }
  const joined = new Uint8Array(total);
  let at = 0;
  for (const chunk of chunks) {
    joined.set(chunk, at);
    at += chunk.length;
  }
  return joined;
}
async function decodeTagPayload(encoded) {
  if (encoded.length > MAX_TAG_PAYLOAD_CHARS) {
    throw new TagError("too_large", `The encoded tag is longer than ${MAX_TAG_PAYLOAD_CHARS} characters.`);
  }
  const json = await gunzip(fromBase64Url(encoded), MAX_TAG_JSON_BYTES);
  try {
    return JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(json));
  } catch {
    throw new TagError("bad_payload", "The tag does not hold valid JSON.");
  }
}
function strictPattern(name) {
  return new RegExp(`<!--\\s*${MARKERS[name]}\\s+v(\\d+)\\s+([A-Za-z0-9_-]*)\\s+-->`, "g");
}
function loosePattern(name) {
  return new RegExp(`<!--\\s*${MARKERS[name]}(?![A-Za-z0-9_-])`, "g");
}
function findTags(body, name) {
  const found = [];
  for (const match of body.matchAll(strictPattern(name))) {
    found.push({
      version: Number(match[1]),
      payload: match[2],
      start: match.index,
      end: match.index + match[0].length
    });
  }
  const mentions = [...body.matchAll(loosePattern(name))].length;
  if (mentions !== found.length) {
    throw new TagError(
      "malformed",
      `The body mentions ${MARKERS[name]} ${mentions} time(s) but holds ${found.length} complete tag(s).`
    );
  }
  return found;
}
async function extractTag(body, name) {
  if (body === void 0 || body === null || body === "") {
    return { status: "none" };
  }
  try {
    const tags = findTags(body, name);
    if (tags.length === 0) {
      return { status: "none" };
    }
    if (tags.length > 1) {
      throw new TagError("duplicate", `The body holds ${tags.length} ${MARKERS[name]} tags; it must hold one.`);
    }
    if (tags[0].version !== TAG_VERSION) {
      throw new TagError(
        "unsupported_version",
        `${MARKERS[name]} v${tags[0].version} is not supported; this reads v${TAG_VERSION}.`
      );
    }
    return { status: "found", value: await decodeTagPayload(tags[0].payload) };
  } catch (cause) {
    if (cause instanceof TagError) {
      return { status: "invalid", code: cause.code, message: cause.message };
    }
    throw cause;
  }
}

// src/gravelmon-tags/dataTag.ts
var MAX_FORMS_PER_DATA_TAG = 25;
var TAG_KEYS = ["kind", "changes"];
var CHANGE_KEYS = ["formId", "ops"];
var OP_KEYS = ["path", "from", "to", "add", "remove"];
function isPlainObject2(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function strayKeys(value, allowed) {
  return Object.keys(value).filter((key) => !allowed.includes(key));
}
function validateDataTag(value) {
  if (!isPlainObject2(value)) {
    return ["The data tag must be a JSON object."];
  }
  const problems = [];
  for (const key of strayKeys(value, TAG_KEYS)) {
    problems.push(`The data tag has an unknown field "${key}".`);
  }
  if (value.kind !== "model") {
    problems.push('The data tag kind must be "model".');
  }
  const changes = value.changes;
  if (!Array.isArray(changes) || changes.length === 0) {
    problems.push("The data tag needs at least one change.");
    return problems;
  }
  if (changes.length > MAX_FORMS_PER_DATA_TAG) {
    problems.push(`A data tag may change at most ${MAX_FORMS_PER_DATA_TAG} forms.`);
    return problems;
  }
  const seen = /* @__PURE__ */ new Set();
  for (const [at, change] of changes.entries()) {
    const where = `changes[${at}]`;
    if (!isPlainObject2(change)) {
      problems.push(`${where}: a change must be an object.`);
      continue;
    }
    for (const key of strayKeys(change, CHANGE_KEYS)) {
      problems.push(`${where}: unknown field "${key}".`);
    }
    if (typeof change.formId === "string") {
      if (seen.has(change.formId)) {
        problems.push(`${where}: ${change.formId} appears twice.`);
      }
      seen.add(change.formId);
    }
    if (Array.isArray(change.ops)) {
      for (const [opAt, op] of change.ops.entries()) {
        if (isPlainObject2(op)) {
          for (const key of strayKeys(op, OP_KEYS)) {
            problems.push(`${where}.ops[${opAt}]: unknown field "${key}".`);
          }
        }
      }
    }
    const patch = { formId: change.formId, ops: change.ops };
    problems.push(...validateChange(patch, "model").map((problem) => `${where}: ${problem}`));
  }
  return problems;
}
async function readDataTag(body) {
  const read = await extractTag(body, "data");
  if (read.status === "none") {
    return { status: "none" };
  }
  if (read.status === "invalid") {
    return { status: "invalid", problems: [read.message] };
  }
  const problems = validateDataTag(read.value);
  return problems.length > 0 ? { status: "invalid", problems } : { status: "ok", tag: read.value };
}

// src/services/remote/rawFileClient.ts
var COBBLEMON_PROJECT_PATH = encodeURIComponent("cable-mc/cobblemon");

// src/gravelmon-tags/notesTag.ts
var MAX_NOTE_CHARS = 240;
var MAX_GAME_HEADING_CHARS = 80;
var NOTES_KEYS = ["kind", "changeLog", "todo"];
function isPlainObject3(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function hasLineBreakOrControl(value) {
  for (let at = 0; at < value.length; at++) {
    const code = value.charCodeAt(at);
    if (code < 32 || code === 127 || code === 8232 || code === 8233) {
      return true;
    }
  }
  return false;
}
function lineProblem(label, value, max) {
  if (typeof value !== "string" || value.trim() === "") {
    return `${label} must be a non empty string.`;
  }
  if (value.length > max) {
    return `${label} is longer than ${max} characters.`;
  }
  if (hasLineBreakOrControl(value)) {
    return `${label} must be a single line.`;
  }
  if (value.includes("<!--") || value.includes("-->")) {
    return `${label} must not contain HTML comment markers.`;
  }
  if (value !== value.trim()) {
    return `${label} must not start or end with a space.`;
  }
  return void 0;
}
function validateModNotes(value) {
  if (!isPlainObject3(value)) {
    return ["The notes tag must be a JSON object."];
  }
  const problems = [];
  for (const key of Object.keys(value).filter((k) => !NOTES_KEYS.includes(k))) {
    problems.push(`The notes tag has an unknown field "${key}".`);
  }
  if (value.kind !== "mod-notes") {
    problems.push('The notes tag kind must be "mod-notes".');
  }
  if (value.changeLog === void 0 && value.todo === void 0) {
    problems.push("The notes tag needs a changeLog or a todo.");
  }
  if (value.changeLog !== void 0) {
    const changeLog = value.changeLog;
    if (!isPlainObject3(changeLog)) {
      problems.push("changeLog must be an object.");
    } else {
      for (const key of Object.keys(changeLog).filter((k) => k !== "game" && k !== "text")) {
        problems.push(`changeLog has an unknown field "${key}".`);
      }
      const game = lineProblem("changeLog.game", changeLog.game, MAX_GAME_HEADING_CHARS);
      const text = lineProblem("changeLog.text", changeLog.text, MAX_NOTE_CHARS);
      if (game !== void 0) problems.push(game);
      if (text !== void 0) problems.push(text);
      if (typeof changeLog.game === "string" && changeLog.game.startsWith("#")) {
        problems.push('changeLog.game must not start with "#".');
      }
    }
  }
  if (value.todo !== void 0) {
    const todo = value.todo;
    if (!isPlainObject3(todo)) {
      problems.push("todo must be an object.");
    } else {
      for (const key of Object.keys(todo).filter((k) => k !== "entry")) {
        problems.push(`todo has an unknown field "${key}".`);
      }
      const entry = lineProblem("todo.entry", todo.entry, MAX_NOTE_CHARS);
      if (entry !== void 0) problems.push(entry);
    }
  }
  return problems;
}
async function readNotesTag(body) {
  const read = await extractTag(body, "notes");
  if (read.status === "none") {
    return { status: "none" };
  }
  if (read.status === "invalid") {
    return { status: "invalid", problems: [read.message] };
  }
  const problems = validateModNotes(read.value);
  return problems.length > 0 ? { status: "invalid", problems } : { status: "ok", notes: read.value };
}

// src/models-ci/runtime.ts
var ConfigError = class extends Error {
};
function requireEnv(env, name) {
  const value = env[name];
  if (value === void 0 || value.trim() === "") {
    throw new ConfigError(`${name} is not set.`);
  }
  return value;
}
function optionalEnv(env, name) {
  const value = env[name];
  return value === void 0 || value.trim() === "" ? void 0 : value.trim();
}
function annotate(level, message) {
  const escaped = message.replace(/%/g, "%25").replace(/\r/g, "%0D").replace(/\n/g, "%0A");
  return `::${level}::${escaped}`;
}
async function readBodyTags(body) {
  return { data: await readDataTag(body), notes: await readNotesTag(body) };
}
function hasAnyTag(tags) {
  return tags.data.status !== "none" || tags.notes.status !== "none";
}
function tagProblems(tags) {
  return [
    ...tags.data.status === "invalid" ? tags.data.problems.map((p) => `data tag: ${p}`) : [],
    ...tags.notes.status === "invalid" ? tags.notes.problems.map((p) => `notes tag: ${p}`) : []
  ];
}

// src/models-ci/applyData.ts
function describeItem(item) {
  const where = item.path === void 0 ? "" : ` at "${item.path}"`;
  const now = item.current === void 0 ? "" : ` (it holds ${JSON.stringify(item.current)} now)`;
  const why = item.reason ?? item.problems?.join(" ") ?? "";
  return `${item.formId}: ${item.status}${where}${now}${why === "" ? "" : ` - ${why}`}`;
}

// src/models-ci/validateData.ts
function pullRequestFromEvent(event) {
  const pr = event.pull_request;
  if (pr === void 0 || typeof pr.number !== "number") {
    throw new Error("This workflow must run on a pull_request event.");
  }
  return {
    number: pr.number,
    body: typeof pr.body === "string" ? pr.body : "",
    baseRef: pr.base?.ref ?? "",
    headRef: pr.head?.ref ?? "",
    merged: pr.merged === true,
    authorLogin: pr.user?.login ?? "",
    authorType: pr.user?.type ?? ""
  };
}
async function runValidateData(pr, appLogin, deps) {
  const log = deps.log ?? ((message) => console.log(message));
  const tags = await readBodyTags(pr.body);
  if (!hasAnyTag(tags)) {
    log(`PR #${pr.number} has no gravelmon-data or gravelmon-notes tag; nothing to validate.`);
    return { exitCode: 0 };
  }
  const failures = [];
  if (!isAppOpened(pr, appLogin)) {
    failures.push(
      `This PR was opened by ${pr.authorLogin === "" ? "an unknown author" : pr.authorLogin}, not by the Gravelmon GitHub App (${appLogin ?? "GRAVELMON_APP_LOGIN is not set"}). Its gravelmon tags would be ignored after the merge: remove them.`
    );
  }
  failures.push(...tagProblems(tags));
  if (failures.length === 0 && tags.data.status === "ok") {
    const answer = await deps.api.post(
      "/api/internal/validate-data-changes",
      { prNumber: pr.number, body: pr.body },
      "any"
    );
    if (answer.outcome !== "ok") {
      const bad = (answer.results ?? []).filter((item) => item.status !== "ok");
      failures.push(
        ...bad.length > 0 ? bad.map((item) => `Data tag cannot be applied - ${describeItem(item)}`) : [`Data tag cannot be applied: the API answered "${answer.outcome}"${answer.problems ? ` (${answer.problems.join(" ")})` : ""}.`]
      );
    }
  }
  if (failures.length === 0) {
    log(`The tags of PR #${pr.number} are valid.`);
    return { exitCode: 0 };
  }
  for (const failure of failures) {
    log(annotate("error", failure));
  }
  return { exitCode: 1 };
}
function readEventFile(env) {
  return pullRequestFromEvent(JSON.parse(readFileSync(requireEnv(env, "GITHUB_EVENT_PATH"), "utf8")));
}
function appLoginFromEnv(env) {
  return optionalEnv(env, "GRAVELMON_APP_LOGIN");
}

// src/models-ci/cli/runCli.ts
function apiFromEnv(env) {
  return new ApiClient({
    domain: requireEnv(env, "GRAVELMON_API_DOMAIN"),
    token: requireEnv(env, "POKEMON_STATUS_INTERNAL_TOKEN")
  });
}
function lazyApiFromEnv(env) {
  let client;
  return {
    post: (path, body, retry) => (client ??= apiFromEnv(env)).post(path, body, retry)
  };
}
async function runCli(main) {
  try {
    const result = await main(process.env, process.argv.slice(2));
    process.exitCode = result.exitCode;
  } catch (cause) {
    console.error(annotate("error", cause instanceof Error ? cause.message : String(cause)));
    process.exitCode = 1;
  }
}

// src/models-ci/cli/validate-data.cli.ts
void runCli((env) => runValidateData(readEventFile(env), appLoginFromEnv(env), { api: lazyApiFromEnv(env) }));
